### ISSUE TITLE
How to contact you

### ISSUE THREAD

**Issue by jagdishgg** [Shreeshrii/imagessan#1]
Dear ,
We have requirement to read a driving license( for 4 countries Oman,UAE,Saudi,Bahrain).We are ready to get customized program for us. Let us know your contact details. Sending as issue as didnt find other way.

**Comment by Shreeshrii** [comment]
Please post in the tesseract-ocr mailing list so that developers who have experience in the kind of project you want can respond.

**Comment by Shreeshrii** [comment]
Jagdish,
I had posted your request in teseerqct-dev and tesseract-ocr groups. There is a response from Ishak DÖLEK  who is interested in developing the program. Please contact them directly.

**Comment by Shreeshrii** [comment]
https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/tesseract-dev/9Iql_MUyRFQ/k_BiFQ5zEQAJ

**Comment by jagdishgg** [comment]
Thanks for your help

**Comment by Shreeshrii** [comment]
Another response


On Tue, 8 Jan 2019, 14:04 Wael Hossam <wael@openmindsys.com wrote:
Dear sir,

Is that your request for developing LPR solution?
Please contact me any time to discuss further.

Best Regards

Wael Hossam

President and CEO

Open Minds CIT
**************************************************
Maadi street 270, Building No.447
Cairo 11742, Egypt

Tel:  +202 27033545
Mobile: +201001223500
www.openmindsys.com
****************************************************


---------- Forwarded message ---------
From: Hamada Fathy Elgnainy <hamada@openmindsys.com>
Date: Tue, Jan 8, 2019 at 6:02 PM
Subject: Re: [tesseract-dev] Fwd: Need programming for custom license plate recognition
To: <tesseract-dev@googlegroups.com>
Cc: wael@openmindsys.com <wael@openmindsys.com>


You are welcome. Our company is interested in developing your lpr projects
